version: "2"
services:
    main:
        hostname: jenkins_main
        build:
            context: .
            dockerfile: Dockerfile.main
        ports:
            - "80:8080"
        networks:
            - jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ../jenkins_data:/var/jenkins_home
            
    worker1:
        hostname: jenkins_worker1
        build:
            context: .
            dockerfile: Dockerfile.deb.worker

        networks:
            - jenkins
        environment:
            SSH_USERNAME: jenkins
            SSH_USERPASS: jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    worker2:
        hostname: jenkins_worker2
        build:
            context: .
            dockerfile: Dockerfile.rpm.worker

        networks:
            - jenkins
        environment:
            SSH_USERNAME: jenkins
            SSH_USERPASS: jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock   
networks:
    jenkins:
